### ISSUE TITLE
Is there a difference with vue-virtual-scroller?

### ISSUE THREAD

**Issue by kimond** [starkwang/vue-virtual-collection#2]
I was wondering if `vue-virtual-collection` works like [vue-virtual-scroller](https://github.com/Akryum/vue-virtual-scroller)? Are the performances the same?

**Comment by starkwang** [comment]
`vue-virtual-scroller` works only for rendering **list**. The item in the list only has the `height` props, just like [List](https://bvaughn.github.io/react-virtualized/#/components/List) in [react-virtualized](https://github.com/bvaughn/react-virtualized)

`vue-virtual-collection` is aimed at efficiently rendering **collection** (contains table, grid, masonry). The item in collection not only has `height` props, but also has `width`, `x`, `y` props, just like [Collection](https://bvaughn.github.io/react-virtualized/#/components/Collection) in react-virtualized

**Comment by starkwang** [comment]
And... I didn't measure the performance difference between this and vue-virtual-scroller.

But I'd like to say, the algorithm used in `vue-virtual-collection` is similar to Collection component in react-virtualized so I think its would be as good as react-virtualized  (without regard to the difference between vue and react).

**Comment by kimond** [comment]
Pretty interesting! Is `vue-virtual-collection` supporting table, grid and masonry? Also, do you plan to support lists or it is already possible to use lists with `vue-virtual-collection`?

**Comment by starkwang** [comment]
You can use [`cellSizeAndPositionGetter`](https://github.com/starkwang/vue-virtual-collection#cellsizeandpositiongetter) to generate any layout you want.

For example, to generate a list layout:
```js
const listWidth = 375;
const itemHeight = 50
function cellSizeAndPositionGetter(item, index) {
    return {
        width: ListWidth,
        height: itemHeight,
        x: itemHeight * index,
        y: 0
    }
}
```

**Comment by kimond** [comment]
Thank you for your fast replies!

**Comment by slidenerd** [comment]
looks good, how to do width: 100% or auto in the cellSizeAndPositionGetter
