### ISSUE TITLE
Is there any possibility for pagemode rendering?

### ISSUE THREAD

**Issue by iskendev** [starkwang/vue-virtual-collection#20]
Didn't find option to render in pagemode, does it exist?

**Comment by starkwang** [comment]
This component should be used in a container which has a known height. It need height to calculate the visibility of items.
So it doesn't support page mode yet, but you can make the container full of page.

**Comment by iskendev** [comment]
So, for this moment there is no option to hide scrollbar?

**Comment by starkwang** [comment]
You can use css to hide the scrollbar.
