### ISSUE TITLE
Vue warn]: Error in mounted hook: "TypeError: Failed to construct 'ResizeObserver': The callback provided as parameter 1 is not a function."

### ISSUE THREAD

**Issue by jinglongji** [starkwang/vue-virtual-collection#26]
mounted() {
        if (ResizeObserver) {
            this.resizeObserver = new ResizeObserver(this.handleResize)
            this.resizeObserver.observe(this.$refs.outer)
        } else {
            this.$refs.outer.addEventListener('resize', this.handleResize)
        }
    },

**Comment by starkwang** [comment]
It's a known bug in 1.4.0. Please update to 1.4.1.
