### ISSUE TITLE
horizontal scrolling?

### ISSUE THREAD

**Issue by wizardnet972** [starkwang/vue-virtual-collection#29]
Does vue-virtual-collection support horizontal scrolling?

**Comment by starkwang** [comment]
Yes, it supports horizontal scrolling by default.

**Comment by wizardnet972** [comment]
@starkwang  Cool! can you share an examples please?

**Comment by starkwang** [comment]
Just as the [Demo](https://starkwang.github.io/vue-virtual-collection/demo/dist/index.html). You can change the amount of columns to a large number.

Here is the [source code of demo](https://github.com/starkwang/vue-virtual-collection/tree/master/demo).
