### ISSUE TITLE
cellSizeAndPosition方法实质是否与this._sectionManager._cellMetadata[displayItem.index]相等

### ISSUE THREAD

**Issue by qq282126990** [starkwang/vue-virtual-collection#3]
```
 computed: {
        cellSizeAndPosition() {
            return this.collection.map((item, index) => this.cellSizeAndPositionGetter(item, index))
        }
}
```
此处的 cellSizeAndPosition方法是否可以用 this._sectionManager._cellMetadata[displayItem.index]去代替一下呢,其实 cellSizeAndPosition的本质是与 this._sectionManager._cellMetadata[displayItem.index]相同的,是否能减少一些代码量呢

**Comment by starkwang** [comment]
嗯，不错的建议，现在计算总高度和宽度的代码还是老的，确实重复调用了 `cellSizeAndPositionGetter `，我下个版本改进一下，能提升初始化的性能

**Comment by starkwang** [comment]
commit: https://github.com/starkwang/vue-virtual-collection/commit/b2d7811750f075764e95b415c366e2038cdfee7d
