### ISSUE TITLE
Generate tables

### ISSUE THREAD

**Issue by robertovaldesperez** [starkwang/vue-virtual-collection#33]
@fisker Is it possible to use vue-virtual-collection to generate tables?

**Comment by fisker** [comment]
Why `@` me?

**Comment by robertovaldesperez** [comment]
@fisker im sorry I thought you could answer the question, since I contacted @starkwang  but did not receive an answer

**Comment by fisker** [comment]
I'll unsubscribe

**Comment by starkwang** [comment]
@robertovaldesperez You can use this component to generate any html block element.

**Comment by robertovaldesperez** [comment]
@starkwang Any example of how to implement a table?
