### ISSUE TITLE
滑动时白屏，这个能否在优化下？？

### ISSUE THREAD

**Issue by fjjjczyz** [starkwang/vue-virtual-collection#5]
你好，是这样子的，我用你的这个组件写了个商品列表，每行4列，每个项目里面有一张图片，还有一些文本，每个商品项目尺寸大概是220pxX400px，当我放进2000个左右商品的时候，滑起来的体验不是很好，很容易白屏，我在想是不是调整成transform:translate3d来控制滑动是不是会有所改善？

**Comment by starkwang** [comment]
See: https://github.com/starkwang/vue-virtual-collection/issues/7
