### ISSUE TITLE
Out-of-bounds array access in getComputedStyle when removing grid items

### ISSUE THREAD

**Issue by TAGC** [starkwang/vue-virtual-collection#9]
I'm trying to make a grid that dynamically adds and removes items from a vue virtual collection based on how the user scrolls. However, when I remove items from the collection, I get errors like this:

```
TypeError: Cannot read property 'width' of undefined
    at VueComponent.getComputedStyle (C:\Users\<me>\Documents\VSCode\atm-prototype\node_modules\vue-virtual-collection\dist\index.js:218:47)
```

This is because in the instances that items get removed from the collection, `getComputedStyle` ends up getting passed `displayItem`s whose index is beyond the bounds of the `cellSizeAndPosition` array:

https://github.com/starkwang/vue-virtual-collection/blob/54911c06274f038a9f3594c74ca9a45b20bc9738/src/VirtualCollection.vue#L105-L114

Unless there's something I'm doing wrong that I could fix on my end, I guess this could be resolved by just adding a check in `getComputedStyle`:

```diff
if (!displayItem) return
- const { width, height, x, y } = this._sectionManager.getCellMetadata(displayItem.index)
+ const cell = this._sectionManager.getCellMetadata(displayItem.index)
+ if (!cell) return
+ const { width, height, x, y } = cell
```

**Comment by TAGC** [comment]
@starkwang Do you have any thoughts on this?

**Comment by starkwang** [comment]
@TAGC Thanks for your issue! Would you want to send a PR for it? Or I will fix it in the next version.
